/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d2a5320c-4b49-4609-aab1-72c3ad634b74",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_uSmr3FXSQ",
    "aws_user_pools_web_client_id": "3mue5m4i8ei0b6q0nmpei65al",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7abhvwq4krcjxoyhvnpqocfpre.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h3jfs6qhpfafpd2zt5zk3qwkqe"
};


export default awsmobile;
